<?php

/**
 * Implements of hook_help()
 *
 */
function xiti_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/build/xiti/add':
    case 'admin/build/xiti/edit/%':
      $output .= '<p>' . t('Here you can define XiTi tags for a specific URL') . '</p>';
      break;
  }
  return $output;
}

/**
 * Implements of hook_permission()
 *
 */
function xiti_permission() {
  return array(
    'administer xiti'  => array(
      'title'           => t('Administer xiti'),
      'description'     => t('Allow to administer xiti default configs.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements of hook_menu()
 *
 */
function xiti_menu() {
  $items = array();

  $items['admin/config/system/xiti'] = array(
    'title'            => 'Xiti settings',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('xiti_settings_form'),
    'access arguments' => array('administer xiti'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'xiti.admin.inc',
  );
  $items['admin/config/system/xiti/settings'] = array(
    'title'  => 'Xiti settings',
    'type'   => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  return $items;
}

function xiti_get_default() {
  $xiti = array();
  if (variable_get('xiti_tagging_plan', 0)) {
    $xiti += array(
      'xiti_xtn2'   => variable_get('xiti_default_xtn2', ''),
      'xiti_xtdi'   => variable_get('xiti_default_xtdi', ''),
      'xiti_xtpage' => '',
    );
  }

  return $xiti;
}

function xiti_generate_snippet($xiti) {
  $xtsd = variable_get('xiti_xtsd', '');
  $noscr_image = variable_get('xiti_noscr_image', '');
  $xtsite = variable_get('xiti_xtsite', '');
  $xiti_js_script = variable_get('xiti_js_script', '');
  $snippet = '';
  if (!isset($xiti['xiti_xtdi'])) {
    $xiti['xiti_xtdi'] = '';
  }
  if ($xtsd !== '' && $noscr_image !== ''
    && $xtsite !== '' && $xiti_js_script !== ''
  ) {
    $snippet .= '<script type="text/javascript"> <!-- ' . "\n";
    $snippet .= 'xtnv = document; ' . "\n";
    $snippet .= 'xtsd = "' . $xtsd . '"; ' . "\n";
    $snippet .= 'xtsite = "' . $xtsite . '"; ' . "\n";
    $snippet .= 'xtn2 = "' . $xiti['xiti_xtn2'] . '"; ' . "\n";
    // TODO: Sanitaize with  xiti_xtpage_filter();
    $snippet .= 'xtpage = "' . $xiti['xiti_xtpage'] . '"; ' . "\n";
    $snippet .= 'xtdi = "' . $xiti['xiti_xtdi'] . '"; ' . "\n";
    $snippet .= ' //--></script>' . "\n";
    $snippet .= '<script type="text/javascript" src="' . $xiti_js_script . '"></script>' . "\n";

    $snippet .= '<noscript>' . "\n";
    $snippet .= '<img width="1" height="1" src="' . $noscr_image . '?s=' . $xtsite . '&amp;s2=' . $xiti['xiti_xtn2'] . '&amp;p=' . $xiti['xiti_xtpage'] . '&amp;di=' . $xiti['xiti_xtdi'] . '" />' . "\n";
    $snippet .= '</noscript>' . "\n";
  }
  return $snippet;
}

function xiti_xtpage_filter($xtpage) {
  $search = array(
    ' ', '"', '#', '%', '&',
    ',', ';', '<', '=', '>',
    '?', '@', '[', '\\', ']',
    '\'', '{', '|', '}'
  );

  $replace = array(
    '_', '', '-', '.', '_',
    '_', '.', '(', '-', ')',
    '.', '.', '(', '/', ')',
    '-', '_', '_', '_'
  );

  $xtpage = str_replace($search, $replace, $xtpage);

  $xtpage = htmlentities($xtpage, ENT_NOQUOTES, 'UTF-8');
  $xtpage = preg_replace('@&(.)[acute|grave|circ|ring|tilde|uml|elig|cedil|slash|zlig]+;@', '$1', $xtpage);

  return html_entity_decode($xtpage);
}
